source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-api.gemspec
gemspec

if File.exist? File.expand_path("../../elasticsearch-v2/elasticsearch-v2.gemspec", __FILE__)
  gem 'elasticsearch-v2', :path => File.expand_path("../../elasticsearch-v2", __FILE__), :require => false
end

if File.exist? File.expand_path("../../elasticsearch-transport-v2", __FILE__)
  gem 'elasticsearch-transport-v2', :path => File.expand_path("../../elasticsearch-transport-v2", __FILE__), :require => true
end

if File.exist? File.expand_path("../../elasticsearch-extensions-v2", __FILE__)
  gem 'elasticsearch-extensions-v2', :path => File.expand_path("../../elasticsearch-extensions-v2", __FILE__), :require => false
end
